version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: group_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - group-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: group_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@group.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - group-network

volumes:
  pgdata:

networks:
  group-network:
    driver: bridge
